env: ${APP_ENV}
db:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_NAME}
jwt:
  secret: ${JWT_SECRET}
brevo:
  api_key: ${BREVO_API_KEY}
  from: ${BREVO_FROM}
app:
  url: ${APP_URL}
