env: ${APP_ENV}
db:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_NAME}
jwt:
  secret: ${JWT_SECRET}
smtp:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  username: ${SMTP_USER}
  password: ${SMTP_PASSWORD}
  from: ${SMTP_FROM}
app:
  url: ${APP_URL}
